# Generated by Django 2.1.3 on 2018-11-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_refund',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_treatment',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_token_refund',
            field=models.IntegerField(default=0, null=True, verbose_name='Nombre de jetons rendus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='staff_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire staff (envoyé par email)'),
        ),
    ]
