# Generated by Django 2.1.3 on 2019-03-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0002_auto_20181106_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.IntegerField(
                choices=[(1, 'Lave-Linge 6Kg'), (2, 'Lave-Linge 6Kg'), (3, 'Sèche-Linge'), (4, 'Monnayeur')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_token_refund',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de jetons rendus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.IntegerField(
                choices=[(1, 'Le linge est bloqué dans la machine (the laundry is stuck inside the machine)'), (
                2, "J'ai mis un jeton mais le cycle n'a pas démarré (I inserted a coin but the cycle didn't start)"),
                         (4, 'La laverie est innondée (the laundry is flooded)'),
                         (5, 'Le monnayeur a été fracturé (the change machine has been broken into)'),
                         (6, 'Autre/Other')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(
                choices=[(0, 'Nouveau'), (1, 'Accepté'), (2, 'Refusé'), (3, 'Terminé (Jetons rendus)')], default=0,
                verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
    ]
