# Generated by Django 2.1.3 on 2019-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0003_auto_20190325_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='email_resp',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   verbose_name='Email resp. laverie du batiment'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(help_text='Uniquement lettre (Ex : A pour le bat A)', max_length=30,
                                   verbose_name='Lettre du batiment'),
        ),
    ]
