# Generated by Django 2.2 on 2019-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0005_auto_20190407_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='email_resp',
            field=models.EmailField(blank=True, max_length=254, null=True,
                                    verbose_name='Email resp. laverie du batiment'),
        ),
    ]
