# Generated by Django 2.2 on 2019-04-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0006_auto_20190407_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(
                choices=[(0, 'Nouveau'), (1, 'Accepté'), (2, 'Refusé'), (3, 'Clos'), (4, 'Expiré')], default=0,
                verbose_name='Etat'),
        ),
    ]
