# Generated by Django 2.2 on 2019-04-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_ticket_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='staff_comment_perm',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire au permanencier'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='staff_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire staff au client (envoyé par email)'),
        ),
    ]
